language: node_js
node_js:
  - "lts/*"

# safelist
branches:
  only:
  - master  

before_install:
  - cd $TRAVIS_BUILD_DIR/front/infinity/  

install:
  - npm install

script:
  - npm run build
  
#https://docs.travis-ci.com/user/deployment/firebase/#generating-your-firebase-token
deploy:
  - proviter: firebase
  token:
    secure: ""