language: node_js
node_js:
  - "lts/*"

#This caches $HOME/.npm or node_modules, depending on the repository’s structure.
cache: npm
    
# safelist
branches:
  only:
  - master  

#[skip <빌드스킵>]

before_install:
  - npm install -g firebase-tools 
install:  
  - cd $TRAVIS_BUILD_DIR/backend/functions/    
  - npm install
  - cd $TRAVIS_BUILD_DIR/front/infinity/  
  - npm install

script:
  - npm run build

before_deploy:
  - cd $TRAVIS_BUILD_DIR/backend/  

deploy:  
  - firebase deploy --token $FIREBASE_TOKEN
#https://docs.travis-ci.com/user/deployment/firebase/#generating-your-firebase-token

# notifications:
#   email:
#     recipients:
#       - jojoldu@gmail.com
    