language: node_js
node_js:
  - "lts/*"

# safelist
branches:
  only:
  - master  

before_install:
  - npm install -g firebase-tools
  - cd $TRAVIS_BUILD_DIR/backend/functions/    
  - npm install
  - cd $TRAVIS_BUILD_DIR/front/infinity/  
  - npm install

script:
  - npm run build
  - cd $TRAVIS_BUILD_DIR/backend/  

after_success:
  - firebase deploy --token $FIREBASE_TOKEN

#https://docs.travis-ci.com/user/deployment/firebase/#generating-your-firebase-token

    